title: "Kyra Trifiletti -- Neuroscience Projects"
author: "Kyra Trifiletti"
description: "Aspiring computational neuroscientist at UC Berkeley"
theme: minima
sass:
  style: compressed
markdown: kramdown

header_pages:
  - index.md
  - projects.md
  - about.md
